[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autorestart=true

[program:horizon]
command=php /var/www/html/artisan horizon
autorestart=true
stdout_logfile=/var/log/horizon.log

[program:queue]
command=php /var/www/html/artisan queue:work --tries=3 --timeout=60
autorestart=true
numprocs=2

[program:scheduler]
command=/bin/sh -c "while [ true ]; do php /var/www/html/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autorestart=true
